### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wurtzelsepp** [nahsra/antisamy#27]
I get.

```
javax.xml.transform.TransformerException: java.lang.ArrayIndexOutOfBoundsException: -1
org.owasp.validator.html.ScanException: javax.xml.transform.TransformerException: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.owasp.validator.html.scan.AntiSamySAXScanner.scan(AntiSamySAXScanner.java:135) ~[antisamy-1.5.7.jar:1.5.7]
	at org.owasp.validator.html.AntiSamy.scan(AntiSamy.java:101) ~[antisamy-1.5.7.jar:1.5.7]
```

When 

```
antiSamy.scan ( "my &test",  antisamypolicy, AntiSamy.SAX ).getCleanHTML (); //used the standard antisamy.xml

```

**Comment by davewichers** [comment]
I can't replicate this bug using AntiSamy 1.5.7. Are you still experiencing this problem? If so, can you provide more details on your setup or some other hints to help me replicate this?

**Comment by davewichers** [comment]
@wurtzelsepp As we can't replicate this, we are closing this for now. But please provide additional details if you still think this is an issue.
