### ISSUE TITLE
GraalVM Support

### ISSUE THREAD

**Issue by adamhenderson** [nahsra/antisamy#340]
Hi,

Am I correct in thinking that currently Antisamy does not support native compilation through GraalVM, from my initial experiments this is the case unfortunately. 

If helpful this is the error I've seen:

Fatal error: 
com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.getType3Message(java.lang.String, char[], java.lang.String, java.lang.String, byte[], int, java.lang.String, byte[]) 
Parsing context:
   at org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.getType3Message(NTLMEngineImpl.java:242)
   at org.apache.hc.client5.http.impl.auth.NTLMEngineImpl.generateType3Msg(NTLMEngineImpl.java:2084)
   at org.apache.hc.client5.http.impl.auth.NTLMScheme.generateAuthResponse(NTLMScheme.java:172)
   at org.apache.hc.client5.http.impl.auth.HttpAuthenticator.addAuthResponse(HttpAuthenticator.java:352)
   at org.apache.hc.client5.http.impl.classic.ConnectExec.createTunnelToTarget(ConnectExec.java:231)
   at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:151)
   at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
   at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
   at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
   at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
   at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
   at org.owasp.validator.css.CssScanner.parseImportedStylesheets(CssScanner.java:328)
   at org.owasp.validator.css.CssScanner.getCleanStylesheetWithImports(CssScanner.java:229)
   at org.owasp.validator.css.CssScanner.scanStyleSheet(CssScanner.java:178)
   at org.owasp.validator.html.scan.AntiSamyDOMScanner.processStyleTag(AntiSamyDOMScanner.java:463)
   at org.owasp.validator.html.scan.AntiSamyDOMScanner.actionValidate(AntiSamyDOMScanner.java:394)
   at org.owasp.validator.html.scan.AntiSamyDOMScanner.recursiveValidateTag(AntiSamyDOMScanner.java:296)
   at org.owasp.validator.html.scan.AntiSamyDOMScanner.processChildren(AntiSamyDOMScanner.java:700)
   at org.owasp.validator.html.scan.AntiSamyDOMScanner.processChildren(AntiSamyDOMScanner.java:692)
   at org.owasp.validator.html.scan.AntiSamyDOMScanner.scan(AntiSamyDOMScanner.java:177)
   at org.owasp.validator.html.AntiSamy.scan(AntiSamy.java:127)
   at org.owasp.validator.html.AntiSamy.scan(AntiSamy.java:105)
   
   GraalVM 22.3-java17

**Comment by kwwall** [comment]
This appears to be a known (closed) issue with GraalVM:
https://github.com/oracle/graal/issues/768
that was closed with some advice given to the issue reporter. Have you
tried that advice to resolve this issue? This appears to be a similar thing.

**Comment by davewichers** [comment]
I have no idea what Graal even is, nor have tested it or anything. Did Kevin's reference answer your question so I can close this?

**Comment by adamhenderson** [comment]
With some digging and Kevins suggestion (thank you) I was able to compile my application to native with GraalVM:
https://www.graalvm.org

quarkus build --native --no-tests -Dquarkus.native.container-build=true -Dquarkus.native.additional-build-args=--trace-object-instantiation=java.security.SecureRandom -Dquarkus.native.additional-build-args=--initialize-at-run-time=org.apache.hc.client5.http.impl.auth.NTLMEngineImpl seemed to work.

Please close.

**Comment by adamhenderson** [comment]
Closed
